### PR TITLE
Fix bundler compatibility

### LINKED ISSUE #235: Bundle compatibility: .contrast is not a function, .deltaE is not a function
## Bug

Using vite@3.2.2 or esbuild@0.15.12

## Reproduce

input.js
```js
import Color from 'colorjs.io'

const red = new Color('red')
const blue = new Color('blue')

// ERROR: .contrast is not a function
red.contrast(blue, 'WCAG21')
// ERROR: .deltaE is not a function
red.deltaE(blue, '2000')

// PASSED
// red.contrastWCAG21(blue)
// red.deltaE2000(blue)
```

bundle:

```bash
esbuild --bundle --minify input.js --outfile=bundle.js && node bundle.js
```

### PR DESCRIPTION
**Pull request by ambar**
Fixes #235 

It's not safe to access function name in bundled apps, such as (reproduced in):
- vite@3.2.2 / esbuild@0.15.12
- cra@5.0.1 / terser@5.15.1 
- next@13.0.1 / swc@1.2

This bug could also reproduced in `dist/color.global.min.js` (main branch, bundled by terser):

```
// eval dist/color.global.min.js 
Color.prototype.contrast -> undefined
```

### CODE REVIEW

**Comment by LeaVerou** [comment]
I'm fine to make the change, though I think it's a bug in these tools if they mess up `func.name`. But are you sure the only calls affected are these two? I'd expect it's a lot more. I need some time to look through the codebase to make sure there aren't more.

**Comment by ambar** [comment]
I've checked all prototype properties, there're only two properties that got renamed:

image

**Comment by LeaVerou** [comment]
@jgerigmeyer what do you think? Fine to merge if it LGTY.

**Comment by jgerigmeyer** [comment]
Looks good on a quick skim, but I'd be happy to take a closer look tomorrow. 👍🏻

File: src/color.js [hunk 1]
```diff
@@ -119,10 +119,6 @@ export default class Color {
 	}
 
 	static defineFunction (name, code, o = code) {
-		if (arguments.length === 1) {
-			[name, code, o] = [arguments[0].name, arguments[0], arguments[0]];
-		}
```
Comment (jgerigmeyer) [inline src/color.js:124]: Remove the corresponding type definition: https://github.com/LeaVerou/color.js/blob/main/types/src/color.d.ts#L93

File: src/color.js [hunk 2]
```diff
@@ -168,12 +164,6 @@ export default class Color {
 		if (exports.register) {
 			exports.register(Color);
 		}
-		else if (exports.default) {
-			Color.defineFunction(exports.default.name, exports.default);
-		}
-		else if (typeof exports === "function") {
-			Color.defineFunction(exports);
-		}
```
Comment (jgerigmeyer) [inline src/color.js:176]: Remove the corresponding type definitions: https://github.com/LeaVerou/color.js/blob/main/types/src/color.d.ts#L105 and https://github.com/LeaVerou/color.js/blob/main/types/src/color.d.ts#L107

**Review by jgerigmeyer — CHANGES_REQUESTED** [review]
@ambar Looks good! Thanks for this contribution. 🚀

One minor request, then this is ready to merge.

File: src/color.js (hunk 2 above)
Comment (ambar) [reply src/color.js:176]: Done!

**Review by jgerigmeyer — APPROVED** [review]

**Comment by carlobeltrame** [comment]
Thanks for the fix! Can we get a release which includes this?

**Comment by LeaVerou** [comment]
Will try to do that tomorrow!

**Comment by LeaVerou** [comment]
Done! Sorry I dropped the ball last week.
